Module2 task1
htmlacademy-javascript/2486211-kekstagram-31 pull request #3
Opened 2024-02-20 23:22 UTC by yourskynas

2024-02-21 13:53 UTC, ademaro commented on index.html
> +  <script src="/js/functions.js"></script>
Указывай относительные пути, а не абсолютные, тк на GitHub Pages не будет работать...

2024-02-21 13:53 UTC, ademaro commented on js/functions.js
> +  if (string.length <= length) {
Можно обойтись без оператора if, а возвращать то, что вернёт оператор сравнения.

2024-02-21 13:54 UTC, ademaro commented on js/functions.js
> +  if (string.length <= length) {
Попробуй написать jsDoc для этой функции.

2024-02-21 13:55 UTC, ademaro commented on js/functions.js
> +  for(let i = newString.length - 1; i >= 0; i--) {
После конструкций языка — ставим пробел (после `for`, `if` и тд)

2024-02-21 13:58 UTC, ademaro requested changes
Оставляю открытым ПР, чтобы попробовать докинуть поправки (новые коммиты) прям в этот ПР.

2024-02-22 06:07 UTC, yourskynas commented on index.html
> +  <script src="/js/functions.js"></script>
Надеюсь, что разобралась правильно. Нужно написать точку "." для обозначения текущий директории и указания относительного пути?

2024-02-22 06:11 UTC, yourskynas commented on index.html
> +  <script src="/js/functions.js"></script>
Надеюсь, что разобралась правильно. Нужно написать точку "." для обозначения текущий директории и указания относительного пути?

2024-02-22 06:14 UTC, yourskynas commented
Новые коммиты сделаны, вопрос только по относительному пути...

2024-02-22 13:13 UTC, merged